ervices:
  # Banco de Dados Postgres
  db:
    image: postgres:15-alpine
    container_name: brevly-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - brevly_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shortener"]
      interval: 5s
      timeout: 5s
      retries: 5

  # API Backend (Fastify)
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: brevly-api
    restart: always
    # O arquivo .env deve estar na raiz da pasta /server
    env_file:
      - ./server/.env
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - DATABASE_URL=postgres://user:pass@db:5432/shortener
      # O Docker agora puxará automaticamente as variáveis do env_file acima
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_ACCESS_KEY_ID=${CLOUDFLARE_ACCESS_KEY_ID}
      - CLOUDFLARE_SECRET_ACCESS_KEY=${CLOUDFLARE_SECRET_ACCESS_KEY}
      - CLOUDFLARE_BUCKET=${CLOUDFLARE_BUCKET}
      - CLOUDFLARE_PUBLIC_URL=${CLOUDFLARE_PUBLIC_URL}
    depends_on:
      db:
        condition: service_healthy

volumes:
  brevly_pgdata: